=== H7KZ/PortfolioV5/static/xml/4iz238/katalog-deskovych-her/katalog-deskovych-her.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns:sch="http://purl.oclc.org/dsdl/schematron"
        xmlns:k="https://jankominek.com/xml/4iz238/katalog-deskovych-her"
        targetNamespace="https://jankominek.com/xml/4iz238/katalog-deskovych-her"
        xmlns="https://jankominek.com/xml/4iz238/katalog-deskovych-her"
        elementFormDefault="qualified">

    <xs:include schemaLocation="katalog-deskovych-her-typy.xsd"/>

    <xs:element name="katalog" type="katalogType">
        <xs:key name="hraIdKey">
            <xs:selector xpath="k:hra"/>
            <xs:field xpath="@id"/>
        </xs:key>

        <xs:key name="hraNazevOriginalKey">
            <xs:selector xpath="k:hra"/>
            <xs:field xpath="k:nazvy/k:nazev_original"/>
        </xs:key>
    </xs:element>

    <xs:complexType name="katalogType">
        <xs:sequence>
            <xs:element name="hra" type="hraType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="hraType">
        <xs:annotation>
            <xs:appinfo>
                <sch:ns prefix="k" uri="https://jankominek.com/xml/4iz238/katalog-deskovych-her"/>

                <sch:pattern>
                    <sch:rule context="k:hraci">
                        <sch:assert test="k:min &lt;= k:max">
                            Minimální počet hráčů (min:<sch:value-of select="k:min"/>) nesmí být větší než maximální
                            (max:<sch:value-of select="k:max"/>).
                        </sch:assert>
                    </sch:rule>

                    <sch:rule context="k:herni_doba">
                        <sch:assert test="k:min &lt;= k:max">
                            Chyba v herní době: Minimální doba (<sch:value-of select="k:min"/>) nesmí být delší než
                            maximální (<sch:value-of select="k:max"/>).
                        </sch:assert>
                    </sch:rule>

                    <sch:rule context="k:hodnoceni">
                        <sch:assert test="count(k:body[@zdroj='Vlastní']) = 1">
                            Každá hra musí mít jedno vlastní hodnocení. Nalezeno:<sch:value-of
                                select="count(k:body[@zdroj='Vlastní'])"/>.
                        </sch:assert>
                    </sch:rule>

                    <sch:rule context="k:obrazky">
                        <sch:assert test="count(k:obrazek[@hlavni='ano']) = 1">
                            Každá hra musí mít vyznačen právě jeden hlavní obrázek (hlavni="ano"). Nalezeno:
                            <sch:value-of select="count(k:obrazek[@hlavni='ano'])"/>.
                        </sch:assert>
                    </sch:rule>
                </sch:pattern>
            </xs:appinfo>
        </xs:annotation>

        <xs:sequence>
            <xs:element name="nazvy" type="nazvyType"/>
            <xs:element name="obrazky" type="obrazkyType"/>
            <xs:element name="autori" type="autoriType"/>
            <xs:element name="vydavatelstvi" type="vydavatelstviType"/>
            <xs:element name="rok_vydani" type="rokVydaniType"/>
            <xs:element name="popis" type="popisType"/>
            <xs:element name="obtiznost" type="obtiznostEnum"/>
            <xs:element name="doporuceny_vek" type="xs:positiveInteger"/>
            <xs:element name="hraci" type="rozsahType"/>
            <xs:element name="herni_doba" type="herniDobaType"/>
            <xs:element name="kategorie_seznam" type="kategorieSeznamType"/>
            <xs:element name="mechaniky_seznam" type="mechanikySeznamType"/>
            <xs:element name="hodnoceni" type="hodnoceniType"/>
            <xs:element name="komponenty_seznam" type="komponentySeznamType"/>
            <xs:element name="cena" type="cenaType"/>
        </xs:sequence>

        <xs:attribute name="id" type="xs:unsignedInt" use="required"/>
    </xs:complexType>

    <xs:complexType name="nazvyType">
        <xs:sequence>
            <xs:element name="nazev_original" type="neprazdnyTextType"/>
            <xs:element name="nazev" type="nazevLokalizovanyType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="nazevLokalizovanyType">
        <xs:simpleContent>
            <xs:extension base="neprazdnyTextType">
                <xs:attribute name="jazyk" type="jazykEnum" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="obrazkyType">
        <xs:sequence>
            <xs:element name="obrazek" type="obrazekType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="obrazekType">
        <xs:simpleContent>
            <xs:extension base="obrazekSouborType">
                <xs:attribute name="hlavni" type="anoNeType" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="autoriType">
        <xs:sequence>
            <xs:element name="autor" type="neprazdnyTextType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="vydavatelstviType">
        <xs:sequence>
            <xs:element name="vydavatel" type="vydavatelType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="vydavatelType">
        <xs:simpleContent>
            <xs:extension base="neprazdnyTextType">
                <xs:attribute name="zeme" type="zemeEnum" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="popisType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="jazyk" type="jazykEnum" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="rozsahType">
        <xs:sequence>
            <xs:element name="min" type="hraciPocetType"/>
            <xs:element name="max" type="hraciPocetType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="herniDobaType">
        <xs:sequence>
            <xs:element name="min" type="dobaHodnotaType"/>
            <xs:element name="max" type="dobaHodnotaType"/>
        </xs:sequence>
        <xs:attribute name="jednotka" type="jednotkaDobyEnum" use="required"/>
    </xs:complexType>

    <xs:complexType name="kategorieSeznamType">
        <xs:sequence>
            <xs:element name="kategorie" type="neprazdnyTextType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="mechanikySeznamType">
        <xs:sequence>
            <xs:element name="mechanika" type="neprazdnyTextType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="hodnoceniType">
        <xs:sequence>
            <xs:element name="body" type="bodyType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="bodyType">
        <xs:simpleContent>
            <xs:extension base="hodnoceniRozsahType">
                <xs:attribute name="zdroj" type="neprazdnyTextType" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="komponentySeznamType">
        <xs:sequence>
            <xs:element name="komponent" type="komponentType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="komponentType">
        <xs:simpleContent>
            <xs:extension base="neprazdnyTextType">
                <xs:attribute name="typ" type="komponentEnum" use="required"/>
                <xs:attribute name="pocet" type="xs:unsignedInt" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="cenaType">
        <xs:simpleContent>
            <xs:extension base="cenaHodnotaType">
                <xs:attribute name="mena" type="menaEnum" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

</xs:schema>

=== H7KZ/PortfolioV5/static/xml/4iz238/katalog-deskovych-her/katalog-deskovych-her.xml
<?xml version="1.0" encoding="UTF-8"?>
<katalog
        xmlns="https://jankominek.com/xml/4iz238/katalog-deskovych-her"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="https://jankominek.com/xml/4iz238/katalog-deskovych-her katalog-deskovych-her.xsd">

    <hra id="1">
        <nazvy>
            <nazev_original>Carcassonne</nazev_original>
            <nazev jazyk="CS">Osadníci z Katanu</nazev>
        </nazvy>
        <obrazky>
            <obrazek hlavni="ano">img/catan/krabice.png</obrazek>
            <obrazek>img/catan/mapa.png</obrazek>
        </obrazky>
        <autori>
            <autor>Klaus Teuber</autor>
        </autori>
        <vydavatelstvi>
            <vydavatel zeme="CZ">Albi</vydavatel>
            <vydavatel zeme="DE">Franckh-Kosmos Verlags-GmbH &amp; Co.</vydavatel>
        </vydavatelstvi>
        <rok_vydani>1995</rok_vydani>
        <popis jazyk="CS">Hráči se ujímají rolí osadníků na nově objeveném ostrově Katan. Budováním
            osad, měst a cest získávají suroviny, se kterými obchodují, aby jako první dosáhli 10
            vítězných bodů.
        </popis>

        <obtiznost>Střední</obtiznost>
        <doporuceny_vek>10</doporuceny_vek>

        <hraci>
            <min>3</min>
            <max>4</max>
        </hraci>

        <herni_doba jednotka="hod">
            <min>1</min>
            <max>1.5</max>
        </herni_doba>

        <kategorie_seznam>
            <kategorie>Strategická</kategorie>
            <kategorie>Rodinná</kategorie>
            <kategorie>Obchodovací</kategorie>
        </kategorie_seznam>

        <mechaniky_seznam>
            <mechanika>Obchodování</mechanika>
            <mechanika>Stavění sítě</mechanika>
            <mechanika>Házení kostkou</mechanika>
            <mechanika>Modulární herní plán</mechanika>
        </mechaniky_seznam>

        <hodnoceni>
            <body zdroj="Vlastní">10.0</body>
            <body zdroj="BGG">7.1</body>
        </hodnoceni>

        <komponenty_seznam>
            <komponent typ="Karty" pocet="95">Karty surovin</komponent>
            <komponent typ="Karty" pocet="25">Karty vývoje</komponent>
            <komponent typ="Desky" pocet="6">Hranice moře</komponent>
            <komponent typ="Desky" pocet="19">Šestiúhelníkové díly krajiny</komponent>
            <komponent typ="Figurky" pocet="96">Herní figurky (města, vesnice, cesty)</komponent>
        </komponenty_seznam>

        <cena mena="CZK">1099</cena>
    </hra>

    <hra id="2">
        <nazvy>
            <nazev_original>Carcassonne</nazev_original>
            <nazev jazyk="CS">Carcassonne</nazev>
        </nazvy>
        <obrazky>
            <obrazek hlavni="ano">img/carcassonne/krabice.png</obrazek>
        </obrazky>
        <autori>
            <autor>Klaus-Jürgen Wrede</autor>
        </autori>
        <vydavatelstvi>
            <vydavatel zeme="CZ">MindOK</vydavatel>
            <vydavatel zeme="DE">Hans im Glück</vydavatel>
        </vydavatelstvi>
        <rok_vydani>2000</rok_vydani>
        <popis jazyk="CS">Hráči postupně přikládají kartičky krajiny a vytvářejí tak cesty, města,
            louky a kláštery. Obsazováním těchto útvarů svými figurkami (Meeples) získávají
            body.
        </popis>

        <obtiznost>Lehká</obtiznost>
        <doporuceny_vek>7</doporuceny_vek>

        <hraci>
            <min>2</min>
            <max>5</max>
        </hraci>

        <herni_doba jednotka="min">
            <min>30</min>
            <max>45</max>
        </herni_doba>

        <kategorie_seznam>
            <kategorie>Rodinná</kategorie>
            <kategorie>Pokládání dílků</kategorie>
        </kategorie_seznam>

        <mechaniky_seznam>
            <mechanika>Pokládání dílků (Tile Placement)</mechanika>
            <mechanika>Ovládání území (Area Control)</mechanika>
        </mechaniky_seznam>

        <hodnoceni>
            <body zdroj="Vlastní">8.5</body>
            <body zdroj="BGG">7.4</body>
        </hodnoceni>

        <komponenty_seznam>
            <komponent typ="Desky" pocet="72">Čtvercové kartičky krajiny</komponent>
            <komponent typ="Figurky" pocet="40">Dřevěné figurky "Meeples"</komponent>
            <komponent typ="Desky" pocet="1">Počítadlo bodů</komponent>
        </komponenty_seznam>

        <cena mena="CZK">599</cena>
    </hra>

    <hra id="3">
        <nazvy>
            <nazev_original>Codenames</nazev_original>
            <nazev jazyk="CS">Krycí jména</nazev>
        </nazvy>
        <obrazky>
            <obrazek hlavni="ano">img/codenames/krabice.png</obrazek>
        </obrazky>
        <autori>
            <autor>Vlaada Chvátil</autor>
        </autori>
        <vydavatelstvi>
            <vydavatel zeme="CZ">CGE</vydavatel>
        </vydavatelstvi>
        <rok_vydani>2015</rok_vydani>
        <popis jazyk="CS">Týmová asociační párty hra. Dva hlavní špióni se snaží jednoslovnými
            nápovědami navést své týmy k odhalení všech správných karet (agentů) na stole.
        </popis>

        <obtiznost>Lehká</obtiznost>
        <doporuceny_vek>10</doporuceny_vek>

        <hraci>
            <min>2</min>
            <max>8</max>
        </hraci>

        <herni_doba jednotka="min">
            <min>15</min>
            <max>20</max>
        </herni_doba>

        <kategorie_seznam>
            <kategorie>Párty</kategorie>
            <kategorie>Slovní</kategorie>
            <kategorie>Dedukční</kategorie>
        </kategorie_seznam>

        <mechaniky_seznam>
            <mechanika>Asociace</mechanika>
            <mechanika>Týmová hra</mechanika>
            <mechanika>Dedukce</mechanika>
        </mechaniky_seznam>

        <hodnoceni>
            <body zdroj="Vlastní">9.0</body>
            <body zdroj="BGG">7.6</body>
        </hodnoceni>

        <komponenty_seznam>
            <komponent typ="Karty" pocet="200">Karty se slovy</komponent>
            <komponent typ="Karty" pocet="40">Karty klíče</komponent>
            <komponent typ="Karty" pocet="16">Karty agentů</komponent>
            <komponent typ="Ostatní" pocet="1">Přesýpací hodiny</komponent>
        </komponenty_seznam>

        <cena mena="CZK">499</cena>
    </hra>

    <hra id="4">
        <nazvy>
            <nazev_original>Ticket to Ride: Europe</nazev_original>
            <nazev jazyk="CS">Jízdenky, prosím! Evropa</nazev>
        </nazvy>
        <obrazky>
            <obrazek hlavni="ano">img/ticket/krabice.png</obrazek>
        </obrazky>
        <autori>
            <autor>Alan R. Moon</autor>
        </autori>
        <vydavatelstvi>
            <vydavatel zeme="CZ">Albi</vydavatel>
            <vydavatel zeme="US">Days of Wonder</vydavatel>
        </vydavatelstvi>
        <rok_vydani>2005</rok_vydani>
        <popis jazyk="CS">Hráči sbírají karty barevných vagónů, aby mohli obsazovat železniční tratě
            napříč Evropou. Body získávají za propojení měst určených tajnými kartami úkolů.
        </popis>

        <obtiznost>Lehká</obtiznost>
        <doporuceny_vek>8</doporuceny_vek>

        <hraci>
            <min>2</min>
            <max>5</max>
        </hraci>

        <herni_doba jednotka="min">
            <min>45</min>
            <max>75</max>
        </herni_doba>

        <kategorie_seznam>
            <kategorie>Rodinná</kategorie>
            <kategorie>Strategická</kategorie>
        </kategorie_seznam>

        <mechaniky_seznam>
            <mechanika>Sbírání sad (Set Collection)</mechanika>
            <mechanika>Stavění sítě</mechanika>
            <mechanika>Správa karet</mechanika>
        </mechaniky_seznam>

        <hodnoceni>
            <body zdroj="Vlastní">8.5</body>
            <body zdroj="BGG">7.5</body>
        </hodnoceni>

        <komponenty_seznam>
            <komponent typ="Desky" pocet="1">Herní plán mapy Evropy</komponent>
            <komponent typ="Figurky" pocet="240">Barevné vagónky a nádraží</komponent>
            <komponent typ="Karty" pocet="156">Herní karty</komponent>
        </komponenty_seznam>

        <cena mena="CZK">1199</cena>
    </hra>

    <hra id="5">
        <nazvy>
            <nazev_original>7 Wonders Duel</nazev_original>
            <nazev jazyk="CS">7 divů světa: Duel</nazev>
        </nazvy>
        <obrazky>
            <obrazek hlavni="ano">img/7wonders_duel/krabice.png</obrazek>
            <obrazek>img/7wonders_duel/karty.png</obrazek>
        </obrazky>
        <autori>
            <autor>Antoine Bauza</autor>
            <autor>Bruno Cathala</autor>
        </autori>
        <vydavatelstvi>
            <vydavatel zeme="CZ">REBEL.cz</vydavatel>
            <vydavatel zeme="FR">Repos Production</vydavatel>
        </vydavatelstvi>
        <rok_vydani>2015</rok_vydani>
        <popis jazyk="CS">Strategická karetní hra výhradně pro dva hráče. Hráči budují svou
            civilizaci získáváním karet z pyramidy. Vítězství lze dosáhnout vojenskou, vědeckou nebo
            kulturní převahou.
        </popis>

        <obtiznost>Střední</obtiznost>
        <doporuceny_vek>10</doporuceny_vek>

        <hraci>
            <min>2</min>
            <max>2</max>
        </hraci>

        <herni_doba jednotka="min">
            <min>30</min>
            <max>45</max>
        </herni_doba>

        <kategorie_seznam>
            <kategorie>Strategická</kategorie>
            <kategorie>Karetní</kategorie>
            <kategorie>Pro dva</kategorie>
        </kategorie_seznam>

        <mechaniky_seznam>
            <mechanika>Draftování karet</mechanika>
            <mechanika>Sbírání sad</mechanika>
        </mechaniky_seznam>

        <hodnoceni>
            <body zdroj="Vlastní">9.5</body>
            <body zdroj="BGG">8.1</body>
        </hodnoceni>

        <komponenty_seznam>
            <komponent typ="Desky" pocet="1">Herní deska konfliktu</komponent>
            <komponent typ="Karty" pocet="73">Karty věků a cechů</komponent>
